version: '3'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -c "npm install && npm start -- --host 0.0.0.0 --port 3000"
    environment:
      - NODE_ENV=development
      - DOCUSAURUS_BASE_URL=/docs-next/
    network_mode: "host"
    restart: unless-stopped 