name: Pull Request Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install -U pip && pip install sphinx_rtd_theme"
        build-command: "make html"
        docs-folder: "."
